resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      circuitBreakerA:
        failureRateThreshold: 30
server:
  port: 14000
spring:
  application:
    name: gateway-server
#下面是关于Spring Cloud Gateway的配置
  cloud:
    gateway:
      routes:
        - id: Consumer
          uri: lb://Consumer
          predicates:
            - Path=/user/signIn
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerA
                fallbackUri: forward:/fallback/circuitBreakerA
      globalcors:
#        配置全局 CORS 策略，[/**] 表示应用于所有路径的请求。
        corsConfigurations:
          '[/**]':
#            允许所有的域名进行跨域请求。
            allowedOrigins: "*"
#            指定允许的 HTTP 方法列表。
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#            允许所有的请求头。
            allowedHeaders: "*"
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eureka10000:10000/eureka,http://eureka10001:10001/eureka"

