server:
  port: 20001
spring:
  application:
    name: "Consumer"
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone : "http://eureka10000:10000/eureka,http://eureka10001:10001/eureka"
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      circuitBreakerA:
        failureRateThreshold: 30
      circuitBreakerB:
        failureRateThreshold: 50
        slowCallRateThreshold: 30
        slowCallDurationThreshold: 2s
  bulkhead:
    instances:
      bulkheadC:
        maxConcurrentCalls: 10
        maxWaitDuration: 20ms
  ratelimiter:
    instances:
      rateLimiterD:
        limitForPeriod: 5
        limitRefreshPeriod: 2s
        timeoutDuration: 20ms
